export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as OurProjects} from './OurProjects'
export {default as Team} from './Team'
export {default as Footer} from './Footer'
export {default as Contact} from './Contact'
